name: CI - Playwright UI & API

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci || npm i
          npx playwright install --with-deps

      - name: Run tests (UI + API)
        env:
          PAYMENT_URL: ${{ secrets.PAYMENT_URL }}
          API_URL: ${{ secrets.API_URL }}
          API_PAYLOAD: ${{ secrets.API_PAYLOAD }} 
          API_TOKEN: ${{ secrets.API_TOKEN }}      
  
        run: npx playwright test tests/UI tests/API --reporter=list,html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
