name: CI - Playwright UI & API

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci || npm i
          npx playwright install --with-deps

      - name: Run UI tests
        env:
          PAYMENT_URL: ${{ secrets.PAYMENT_URL }}  # שים ב-Secrets
        run: npx playwright test tests/ui --reporter=html

      - name: Run API tests
        env:
          API_URL: ${{ secrets.API_URL }}          # שים ב-Secrets
        run: npx playwright test tests/api --reporter=html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
